"use client";

import { useState } from "react";
import { Clock, Download } from "lucide-react";

interface Props {
  data: any;
  petName: string;
}

const SECTIONS = [
  { key: "feeding",  label: "🍽️ Feeding",   color: "#FDF0D5", border: "#C47A10" },
  { key: "exercise", label: "🏃 Exercise",   color: "#E3EFF8", border: "#3A7AB5" },
  { key: "grooming", label: "✂️ Grooming",   color: "#EDE8F9", border: "#7A5CB5" },
  { key: "health",   label: "💊 Health",     color: "#F9EDE8", border: "#C8593A" },
  { key: "mental",   label: "🧠 Mental",     color: "#F2F7EC", border: "#4A7C28" },
];

export default function PetCareResult({ data, petName }: Props) {
  const [activeTab, setActiveTab] = useState("feeding");

  function handlePrint() {
    window.print();
  }

  if (!data) return null;

  return (
    <div className="mt-6 space-y-5">

      {/* Summary card */}
      <div className="bg-white border rounded-2xl p-6"
        style={{ borderColor: "rgba(45,80,22,0.1)" }}>
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h2 className="font-display text-xl font-bold text-gray-900">
              {petName}'s Personalized Care Plan
            </h2>
            <p className="text-xs mt-1" style={{ color: "#8A9480" }}>
              Generated by Claude AI · Veterinary-grade recommendations
            </p>
          </div>
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium border flex-shrink-0"
            style={{ borderColor: "rgba(45,80,22,0.2)", color: "#2D5016" }}
          >
            <Download className="w-3.5 h-3.5" /> Save / Print
          </button>
        </div>
        <p className="text-sm leading-relaxed" style={{ color: "#4A7C28" }}>
          {data.summary}
        </p>

        {/* Urgent advice */}
        {data.urgentAdvice && (
          <div className="mt-4 p-4 rounded-xl border-l-4"
            style={{ backgroundColor: "#F9EDE8", borderColor: "#C8593A" }}>
            <p className="text-xs font-semibold mb-1" style={{ color: "#C8593A" }}>
              ⚠️ Important Note
            </p>
            <p className="text-sm" style={{ color: "#C8593A" }}>{data.urgentAdvice}</p>
          </div>
        )}
      </div>

      {/* Tab navigation */}
      <div className="flex gap-2 flex-wrap">
        {SECTIONS.map((s) => (
          <button
            key={s.key}
            onClick={() => setActiveTab(s.key)}
            className="px-4 py-2 rounded-xl text-sm font-medium border transition-all"
            style={activeTab === s.key
              ? { backgroundColor: "#2D5016", color: "#fff", borderColor: "#2D5016" }
              : { backgroundColor: "#fff", color: "rgba(45,80,22,0.7)", borderColor: "rgba(45,80,22,0.15)" }}
          >
            {s.label}
          </button>
        ))}
        <button
          onClick={() => setActiveTab("schedule")}
          className="px-4 py-2 rounded-xl text-sm font-medium border transition-all"
          style={activeTab === "schedule"
            ? { backgroundColor: "#2D5016", color: "#fff", borderColor: "#2D5016" }
            : { backgroundColor: "#fff", color: "rgba(45,80,22,0.7)", borderColor: "rgba(45,80,22,0.15)" }}
        >
          📅 Daily Schedule
        </button>
      </div>

      {/* Feeding */}
      {activeTab === "feeding" && data.feeding && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">🍽️ Feeding Plan</h3>
          <div className="grid sm:grid-cols-3 gap-4 mb-5">
            {[
              { label: "Meals per Day", value: data.feeding.mealsPerDay },
              { label: "Portion Size", value: data.feeding.portionSize },
              { label: "Feeding Times", value: data.feeding.feedingTimes?.join(", ") },
            ].map((item) => (
              <div key={item.label} className="rounded-xl p-4 text-center"
                style={{ backgroundColor: "#FAF7F2" }}>
                <div className="text-xs mb-1" style={{ color: "#8A9480" }}>{item.label}</div>
                <div className="font-display text-base font-bold" style={{ color: "#2D5016" }}>
                  {item.value}
                </div>
              </div>
            ))}
          </div>
          <InfoSection title="Recommended Food" content={data.feeding.recommendedFood} />
          <ListSection title="✅ Feeding Tips" items={data.feeding.tips} color="#2D5016" bg="#F2F7EC" />
          <ListSection title="❌ Foods to Avoid" items={data.feeding.avoid} color="#C8593A" bg="#F9EDE8" />
        </div>
      )}

      {/* Exercise */}
      {activeTab === "exercise" && data.exercise && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">🏃 Exercise Plan</h3>
          <div className="grid sm:grid-cols-2 gap-4 mb-5">
            {[
              { label: "Daily Exercise", value: `${data.exercise.dailyMinutes} minutes` },
              { label: "Sessions per Day", value: data.exercise.sessions },
            ].map((item) => (
              <div key={item.label} className="rounded-xl p-4 text-center"
                style={{ backgroundColor: "#E3EFF8" }}>
                <div className="text-xs mb-1" style={{ color: "#3A7AB5" }}>{item.label}</div>
                <div className="font-display text-xl font-bold" style={{ color: "#185FA5" }}>
                  {item.value}
                </div>
              </div>
            ))}
          </div>
          <ListSection title="🏅 Recommended Activities" items={data.exercise.activities} color="#3A7AB5" bg="#E3EFF8" />
          <ListSection title="💡 Exercise Tips" items={data.exercise.tips} color="#2D5016" bg="#F2F7EC" />
          {data.exercise.warning && (
            <div className="mt-4 p-4 rounded-xl border-l-4"
              style={{ backgroundColor: "#FDF0D5", borderColor: "#C47A10" }}>
              <p className="text-xs font-semibold mb-1" style={{ color: "#C47A10" }}>⚠️ Note</p>
              <p className="text-sm" style={{ color: "#8A5C00" }}>{data.exercise.warning}</p>
            </div>
          )}
        </div>
      )}

      {/* Grooming */}
      {activeTab === "grooming" && data.grooming && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">✂️ Grooming Schedule</h3>
          <div className="grid sm:grid-cols-2 gap-3 mb-5">
            {[
              { label: "Brushing", value: data.grooming.brushingFrequency },
              { label: "Bathing",  value: data.grooming.bathingFrequency },
              { label: "Nail Trimming", value: data.grooming.nailTrimming },
              { label: "Ear Cleaning",  value: data.grooming.earCleaning },
            ].map((item) => (
              <div key={item.label} className="flex items-center gap-3 p-3 rounded-xl"
                style={{ backgroundColor: "#EDE8F9" }}>
                <div className="flex-1">
                  <div className="text-xs" style={{ color: "#7A5CB5" }}>{item.label}</div>
                  <div className="text-sm font-medium" style={{ color: "#4A2D8A" }}>{item.value}</div>
                </div>
              </div>
            ))}
          </div>
          <InfoSection title="🦷 Dental Care" content={data.grooming.dentalCare} />
          <ListSection title="💡 Grooming Tips" items={data.grooming.tips} color="#7A5CB5" bg="#EDE8F9" />
        </div>
      )}

      {/* Health */}
      {activeTab === "health" && data.health && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">💊 Health Care</h3>
          <div className="grid sm:grid-cols-2 gap-3 mb-5">
            {[
              { label: "Vet Visits",  value: data.health.vetVisits },
              { label: "Deworming",   value: data.health.deworming },
              { label: "Flea & Tick", value: data.health.fleaTick },
            ].map((item) => (
              <div key={item.label} className="p-3 rounded-xl"
                style={{ backgroundColor: "#F9EDE8" }}>
                <div className="text-xs" style={{ color: "#C8593A" }}>{item.label}</div>
                <div className="text-sm font-medium mt-0.5" style={{ color: "#8B2500" }}>{item.value}</div>
              </div>
            ))}
          </div>
          <ListSection title="💉 Vaccination Schedule" items={data.health.vaccinations} color="#C8593A" bg="#F9EDE8" />
          <ListSection title="👁️ Watch Out For" items={data.health.watchFor} color="#C8593A" bg="#F9EDE8" />
        </div>
      )}

      {/* Mental */}
      {activeTab === "mental" && data.mental && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">🧠 Mental Enrichment</h3>
          <InfoSection title="👥 Social Needs" content={data.mental.socialNeeds} />
          <ListSection title="🎮 Enrichment Activities" items={data.mental.enrichmentActivities} color="#4A7C28" bg="#F2F7EC" />
          <ListSection title="🎓 Training Tips" items={data.mental.trainingTips} color="#4A7C28" bg="#F2F7EC" />
        </div>
      )}

      {/* Daily Schedule */}
      {activeTab === "schedule" && data.dailySchedule && (
        <div className="bg-white border rounded-2xl p-6"
          style={{ borderColor: "rgba(45,80,22,0.1)" }}>
          <h3 className="font-display text-lg font-semibold mb-4">
            📅 {petName}'s Daily Schedule
          </h3>
          <div className="space-y-3">
            {data.dailySchedule.map((item: any, i: number) => (
              <div key={i} className="flex items-center gap-4 p-3 rounded-xl"
                style={{ backgroundColor: i % 2 === 0 ? "#FAF7F2" : "#F2F7EC" }}>
                <div className="flex items-center gap-2 flex-shrink-0 w-24">
                  <Clock className="w-3.5 h-3.5 flex-shrink-0" style={{ color: "#4A7C28" }} />
                  <span className="text-xs font-medium" style={{ color: "#2D5016" }}>
                    {item.time}
                  </span>
                </div>
                <div className="flex-1">
                  <span className="text-sm font-medium text-gray-900">{item.activity}</span>
                </div>
                <div className="text-xs flex-shrink-0" style={{ color: "#8A9480" }}>
                  {item.duration}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Disclaimer */}
      <div className="rounded-xl p-4 text-xs" style={{ backgroundColor: "#FAF7F2", color: "#8A9480" }}>
        <strong style={{ color: "#4A7C28" }}>Disclaimer:</strong> These recommendations are generated by AI and are meant as a general guide. 
        Always consult with a licensed veterinarian for medical advice specific to your pet's health needs.
      </div>
    </div>
  );
}

// Helper components
function InfoSection({ title, content }: { title: string; content: string }) {
  if (!content) return null;
  return (
    <div className="mb-4">
      <p className="text-xs font-semibold mb-1.5" style={{ color: "#2D5016" }}>{title}</p>
      <p className="text-sm leading-relaxed" style={{ color: "#4A7C28" }}>{content}</p>
    </div>
  );
}

function ListSection({ title, items, color, bg }: {
  title: string; items: string[]; color: string; bg: string;
}) {
  if (!items?.length) return null;
  return (
    <div className="mb-4">
      <p className="text-xs font-semibold mb-2" style={{ color }}>{ title}</p>
      <ul className="space-y-1.5">
        {items.map((item: string, i: number) => (
          <li key={i} className="flex items-start gap-2 text-sm px-3 py-2 rounded-lg"
            style={{ backgroundColor: bg }}>
            <span className="flex-shrink-0 mt-0.5" style={{ color }}>•</span>
            <span style={{ color }}>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
